platform :ios, '13.0'

target 'WordSkill-Alireza-Toghyiani-Iran' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Emami
  pod 'RxSwift'
  pod 'Alamofire', '~> 5.0.0'
  pod 'BRYXBanner'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'Kingfisher'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'MessageKit'

end
